### ISSUE TITLE
PIRTO CARD PCB analysis

### ISSUE THREAD

**Issue by Fing972** [aotta/PiRTO#1]
Good morning, 
First of all I would like to congratulate you on the project, I have been following a way to create a multicard cartridge for Intellivision at home for a long time.
I have already followed the project with the Teensy but I think it is too expensive and that the project can be created even with similar cheaper boards.
Coming to the point I saw that the main problem is the operation at 3.3v (PI-PICO) and 5v (Intv).
Studying the diagram I was trying to understand if it is possible to use other components instead of the 74LVC245.
I've seen other alternative components like the Cd4050 or other level shifters. 
What I haven't yet understood is whether "bidirectional" communication must take place on some pins of the cartridge.
In the case of "bidirectional" communication it is necessary that if a signal arrives from the INTV(output) at 5V on a PIN of the cartridge  it must be translated to 3.3V for the PI-PICO(input), but if on the "same" PIN a signal then arrives from the PI-PICO(output) to INTV(input) must be translated from 3.3v to 5V.
If so I would understand the need to use a 74LVC245 which also has the DIR function which reverses the flow on the 8 channels. If this is not the case the project could be greatly simplified.
From what I have read the signals coming from the INTV must necessarily be converted from 5v to 3.3v for the PI-PICO. But for the reverse situation it may not be necessary to use anything since a 3.3v signal is generally identified as HIGH.
I have made a long introduction but in conclusion I would like to understand if the communication on the various PINs is unidirectional, i.e. input or output
Thanks, regards

**Comment by aotta** [comment]
Level shifter is not really necessary since rp2040 can tolerate 5v input (not 5,5v, that's whay pico couldn't be defined "5V tolerant"), and PiRTO II doesn't use at all level shifters. So I simply suggest to move to PiRTO II projects, and can't consider this as an issue, so i close it.

**Comment by Fing972** [comment]
Thanks for your answer,
my intention was only to comment on the project and not highlight an operating problem. 
Taking advantage of the opportunity, since you mentioned the Pirto II project I just wanted to know if there was a particular reason why a PI Purple raspberry was used or if another model could be used (original or clone like yd-rp2040) naturally adapting the scheme.
I didn't know that Raspberry PI picos were 5v tolerant.
Thank you.
